// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using alarm_service.Data;

#nullable disable

namespace alarm_service.Migrations
{
    [DbContext(typeof(AlarmDbContext))]
    [Migration("20260623044910_InitialAlarmDomainSchema")]
    partial class InitialAlarmDomainSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("alarm_service.Entities.CEAAlarm", b =>
                {
                    b.Property<int>("CEAAlarmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("CEAAlarmId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CEAAlarmId"));

                    b.Property<string>("AlarmType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("AlarmType");

                    b.Property<DateTime?>("ClearedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ClearedTime");

                    b.Property<int>("DeviceId")
                        .HasColumnType("integer")
                        .HasColumnName("DeviceId");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("IsActive");

                    b.Property<DateTime>("RaisedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("RaisedTime");

                    b.HasKey("CEAAlarmId");

                    b.ToTable("CEAAlarm", (string)null);
                });

            modelBuilder.Entity("alarm_service.Entities.MSANAlarm", b =>
                {
                    b.Property<int>("MSANAlarmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("MSANAlarmId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MSANAlarmId"));

                    b.Property<string>("AlarmType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("AlarmType");

                    b.Property<DateTime?>("ClearedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ClearedTime");

                    b.Property<int>("DeviceId")
                        .HasColumnType("integer")
                        .HasColumnName("DeviceId");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("IsActive");

                    b.Property<DateTime>("RaisedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("RaisedTime");

                    b.HasKey("MSANAlarmId");

                    b.ToTable("MSANAlarm", (string)null);
                });

            modelBuilder.Entity("alarm_service.Entities.SLBNAlarm", b =>
                {
                    b.Property<int>("SLBNAlarmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("SLBNAlarmId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SLBNAlarmId"));

                    b.Property<string>("AlarmType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("AlarmType");

                    b.Property<DateTime?>("ClearedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ClearedTime");

                    b.Property<int>("DeviceId")
                        .HasColumnType("integer")
                        .HasColumnName("DeviceId");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("IsActive");

                    b.Property<DateTime>("RaisedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("RaisedTime");

                    b.HasKey("SLBNAlarmId");

                    b.ToTable("SLBNAlarm", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
