-- Manual provisioning for the correlation result store.
-- This is intentionally separate from the existing alarm migration, as documented
-- in Plus-Correlation-plan.md. Run against the alarm-service PostgreSQL database.

CREATE TABLE IF NOT EXISTS "RootCauses" (
    "RootCauseId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "DeviceId" integer NOT NULL,
    "AlarmId" integer NOT NULL,
    "RootCauseType" varchar(100) NOT NULL,
    "SourceDeviceType" varchar(50) NOT NULL DEFAULT '',
    "CorrelationRuleName" varchar(150) NOT NULL DEFAULT '',
    "CreatedAt" timestamp with time zone NOT NULL
);

CREATE INDEX IF NOT EXISTS "IX_RootCauses_DeviceId" ON "RootCauses" ("DeviceId");
CREATE INDEX IF NOT EXISTS "IX_RootCauses_AlarmId" ON "RootCauses" ("AlarmId");
ALTER TABLE "RootCauses" ADD COLUMN IF NOT EXISTS "SourceDeviceType" varchar(50) NOT NULL DEFAULT '';
ALTER TABLE "RootCauses" ADD COLUMN IF NOT EXISTS "CorrelationRuleName" varchar(150) NOT NULL DEFAULT '';

CREATE TABLE IF NOT EXISTS "ImpactedDevices" (
    "ImpactedDeviceId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "RootCauseId" integer NOT NULL REFERENCES "RootCauses" ("RootCauseId") ON DELETE CASCADE,
    "DeviceId" integer NOT NULL,
    "DeviceType" varchar(50) NOT NULL DEFAULT '',
    "ImpactType" varchar(100) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);

CREATE INDEX IF NOT EXISTS "IX_ImpactedDevices_RootCauseId" ON "ImpactedDevices" ("RootCauseId");
CREATE INDEX IF NOT EXISTS "IX_ImpactedDevices_DeviceId" ON "ImpactedDevices" ("DeviceId");
ALTER TABLE "ImpactedDevices" ADD COLUMN IF NOT EXISTS "DeviceType" varchar(50) NOT NULL DEFAULT '';

CREATE TABLE IF NOT EXISTS "CorrelatedFaults" (
    "CorrelatedFaultId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "RootCauseId" integer NOT NULL REFERENCES "RootCauses" ("RootCauseId") ON DELETE CASCADE,
    "CorrelationRuleName" varchar(150) NOT NULL,
    "SourceDeviceId" integer NOT NULL,
    "SourceDeviceType" varchar(50) NOT NULL,
    "SourceAlarmId" integer NOT NULL,
    "SourceAlarmType" varchar(100) NOT NULL,
    "StartedAt" timestamp with time zone NOT NULL,
    "EndedAt" timestamp with time zone NULL,
    "Status" varchar(30) NOT NULL,
    "ConfidenceScore" numeric NOT NULL
);

CREATE INDEX IF NOT EXISTS "IX_CorrelatedFaults_RootCauseId" ON "CorrelatedFaults" ("RootCauseId");
CREATE INDEX IF NOT EXISTS "IX_CorrelatedFaults_Source" ON "CorrelatedFaults" ("SourceDeviceType", "SourceAlarmId");

CREATE TABLE IF NOT EXISTS "CorrelatedFaultAlarms" (
    "CorrelatedFaultAlarmId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CorrelatedFaultId" integer NOT NULL REFERENCES "CorrelatedFaults" ("CorrelatedFaultId") ON DELETE CASCADE,
    "AlarmId" integer NOT NULL,
    "DeviceId" integer NOT NULL,
    "DeviceType" varchar(50) NOT NULL,
    "AlarmType" varchar(100) NOT NULL,
    "RaisedTime" timestamp with time zone NOT NULL
);

CREATE INDEX IF NOT EXISTS "IX_CorrelatedFaultAlarms_Alarm" ON "CorrelatedFaultAlarms" ("DeviceType", "AlarmId");
